[font]
size = 12.5
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }

[env]
TERM = "alacritty"

[window]
option_as_alt = "OnlyLeft"

[general]
import = [
    "./themes/kanagawa_dragon.toml"
]
