[font]
size = 12.5
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }

[env]
TERM = "alacritty"



## NATURAL TEXT EDITING KEYBINDS FOR MAC!
## TODO: make this load only on MacOS [https://github.com/abhinavchadaga/dotfiles/issues/1]
[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u001b\u007f"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005"

[[keyboard.bindings]]
key = "Delete"
chars = "\u0004"

[[keyboard.bindings]]
key = "Delete"
mods = "Alt"
chars = "\u001bd"

[general]
import = [
    "./themes/kanagawa_dragon.toml"
]
